services:
  storage-nodes-graph:
    container_name: storagenodesgraph
    build: .
    ports:
      - "8080:80"
    restart: unless-stopped
    volumes:
      - ./data:/data
    environment:
      - STORAGE_NODES=storagenode1:14002,storagenode2:14002
      - GRAPH1_HISTORY=1week
      - GRAPH1_WIDTH=1000
      - GRAPH1_HEIGHT=250
      - GRAPH2_HISTORY=5weeks
      - GRAPH2_WIDTH=1000
      - GRAPH2_HEIGHT=250
      - NVG_URL=
      - NVG_SECRET=mysecretkey
